### ISSUE TITLE
Endnote fixes

### ISSUE THREAD

**Issue by robinwhittleton** [EmmaSweeney/ludovico-ariosto_orlando-furioso_william-stewart-rose#6]
- note-2 “Coleridges” -> “Coleridge’s”
- note-82 “assage” -> “passage”
- note-93 “giacinto” presumably needs lang
- note-102 “voeem” looks like “vocem” in the scans, but I’m at a loss for the translation
- note-141 “oints” -> “points”
- note-197 “Wasco” -> “Vasco”
- note-202 “Wasto” -> “Vasto”
- note-218 “eneral” -> “general” and “orm” -> “form”
- note-237 “Innamorato” should be italicised as a poem
- note-252 “aggear” -> “appear”
- note-274 “Uunfortunately” -> “Unfortunately” and “maintaing” -> “maintaining”
- note-358 “kili” -> “kill”
- note-384 “arius” -> “Marius”
- note-386 couple of books need italicisation
- note-397 “1eady” -> “ready”
- note-446 “Il Cortigiano” and “Girone il Cortese” need lang and publication italicisation
- note-448 “ome” -> “Rome”
- note-481 “ame” -> “game” and “ike” -> “like”
- note-501 “Wenice” -> “Venice”
- note-507 broken death date. Jacopo Sadoleto died 1547. Also poems need italicisation.
- note-556 “Wasto” -> “Vasto”
- note-568 “Watican” -> “Vatican”
- note-570 poems need italicisation
- note-517 “divino” and “flagello de’ principi” need lang italicisation
- note-569 “Woltera” -> “Voltera”
- note-570 “Warino” -> “Varino”
- note-573 “Walerio” -> “Valerio”
- note-575 “Walerio” -> “Valerio”
- note-582: “th:” -> “the”

**Comment by EmmaSweeney** [comment]
note-507: I didn't add italics because these poems are short and the titles are names.
