### ISSUE TITLE
se-mismatched-dashes and se-mismatched-diacritics find loads of potentials

### ISSUE THREAD

**Issue by robinwhittleton** [EmmaSweeney/ludovico-ariosto_orlando-furioso_william-stewart-rose#8]
Could you review the output and double-check? I ended up fixing a bunch of dash mismatches in _Kalevala_ after @acabal’s prompting so we do do this sometimes to poetry. See https://github.com/standardebooks/elias-lonnrot_the-kalevala_john-martin-crawford/commit/407b7973b3000faf966455a153e00a768f3f5142.

**Comment by EmmaSweeney** [comment]
Of course I forgot to run these 🤦‍♀️

For `se find-mismatched-diacritics .` the rest of the differences are because of the Italian sections and various Italian names.
